In [51]:
import requests
import pandas as pd
from datetime import datetime

In [52]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = datetime.now().year - 5   # last 5 years
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place": p.get("place"),
                "status": p.get("status"),
                "tsunami": p.get("tsunami"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "magError": p.get("magError"),
                "depthError": p.get("depthError"),
                "magNst": p.get("magNst"),
                "locationSource": p.get("locationSource"),
                "magSource": p.get("magSource"),
                "types": p.get("types"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "type": p.get("type")  # Event type
            })

df = pd.DataFrame(all_records)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print(df.head())

Rows: 108801
Columns: 26
           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...    gap  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   42.0
1                                        Fiji region  reviewed  ...   64.0
2                    103 km SW of Basco, Philippines  reviewed  ...  106.0
3                            114 km N of M?n?b, Iran  reviewed  ...   71.0
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   65.0

   magError depthError  magNst  locationSource  magSource  \
0      None       None    None            None       None
1      None       None    None            None       None
2      None       None    None            None       None
3      None       None    None            None       None
4      None       None    None            None       None

                                    types           ids sources        type
0  ,dyfi,moment-tensor,origin,phase-data,  ,us6000ddi8,    ,us,  earthquake
1                     ,origin,phase-data,  ,us6000dev6,    ,us,  earthquake
2                     ,origin,phase-data,  ,us6000dev5,    ,us,  earthquake
3                     ,origin,phase-data,  ,us6000ddhs,    ,us,  earthquake
4                     ,origin,phase-data,  ,us6000dev4,    ,us,  earthquake

[5 rows x 26 columns]

In [53]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'magError', 'depthError', 'magNst', 'locationSource',
       'magSource', 'types', 'ids', 'sources', 'type'],
      dtype='object')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108801 entries, 0 to 108800
Data columns (total 26 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              108801 non-null  object
 1   time            108801 non-null  datetime64[ns]
 2   updated         108801 non-null  datetime64[ns]
 3   latitude        108801 non-null  float64
 4   longitude       108801 non-null  float64
 5   depth_km        108801 non-null  float64
 6   mag             108801 non-null  float64
 7   magType         108801 non-null  object
 8   place           108801 non-null  object
 9   status          108801 non-null  object
 10  tsunami         108801 non-null  int64
 11  sig             108801 non-null  int64
 12  net             108801 non-null  object
 13  nst             81040 non-null   float64
 14  dmin            104828 non-null  float64
 15  rms             108783 non-null  float64
 16  gap             105780 non-null  float64
 17  magError        0 non-null       object
 18  depthError      0 non-null       object
 19  magNst          0 non-null       object
 20  locationSource  0 non-null       object
 21  magSource       0 non-null       object
 22  types           108801 non-null  object
 23  ids             108801 non-null  object
 24  sources         108801 non-null  object
 25  type            108801 non-null  object
dtypes: datetime64[ns](2), float64(8), int64(2), object(14)
memory usage: 21.6+ MB

In [55]:
df.describe()

,time,updated,latitude,longitude,depth_km,mag,tsunami,sig,nst,dmin,rms,gap
count,108801,108801,108801.000000,108801.000000,108801.000000,108801.000000,108801.000000,108801.000000,81040.000000,104828.000000,108783.000000,105780.000000
mean,2023-08-10 14:35:58.960023552,2023-11-28 02:23:31.403509760,12.055627,7.049569,72.116539,4.258689,0.006048,287.852428,45.441153,3.182792,0.656190,122.090990
min,2021-01-01 00:14:07.580000,2021-01-01 10:15:32.601000,-84.493200,-179.999700,-3.740000,3.000000,0.000000,138.000000,0.000000,0.000000,0.000000,8.000000
25%,2022-03-29 18:35:26.406000128,2022-07-26 14:54:51.211000064,-14.824900,-114.146600,10.000000,4.000000,0.000000,248.000000,20.000000,0.830000,0.490000,75.000000
50%,2023-08-08 04:54:36.263000064,2024-01-10 06:01:38.040000,14.999500,23.127900,21.230000,4.300000,0.000000,284.000000,32.000000,1.807000,0.650000,113.000000
75%,2024-12-31 15:18:02.588000,2025-04-26 14:47:09.040000,38.952200,130.531600,71.575000,4.600000,0.000000,326.000000,56.000000,3.709000,0.820000,155.000000
max,2026-03-30 11:45:29.419000,2026-03-30 12:24:03.040000,87.375200,179.999400,681.238000,8.800000,1.000000,2910.000000,619.000000,62.558000,2.820000,358.180000
std,NaN,NaN,32.106555,128.966953,123.632800,0.609424,0.077532,91.587298,39.458161,4.450806,0.257844,62.896518

In [56]:
df.shape

(108801, 26)

In [57]:
import re

def extract_country(place: str) -> str:
    if not place or not isinstance(place, str):
        return None
    
    if "," in place:
        return place.split(",")[-1].strip()
    
    match = re.search(r"([A-Za-z\s]+)$", place)
    return match.group(1).strip() if match else None

In [58]:
string_fields = ["magType", "status", "type", "net", "sources", "types"]

for col in string_fields:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.lower()

In [59]:
df["country"] = df["place"].apply(extract_country)

In [60]:
# Normalize alert
if "alert" in df.columns:
    df["alert"] = df["alert"].astype(str).str.lower()

# Clean string fields
string_fields = ["magType", "status", "type", "net", "sources", "types"]
for col in string_fields:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.lower()

# Extract country
df["country"] = df["place"].apply(extract_country)

In [61]:
numeric_fields = [
    "mag", "depth_km", "nst", "dmin", "rms", "gap",
    "magError", "depthError", "magNst", "sig"
]

for col in numeric_fields:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [62]:
for col in numeric_fields:
    if col in df.columns:
        median_val = df[col].median()
        if pd.isna(median_val):   # if column is entirely NaN
            df[col] = df[col].fillna(0)
        else:
            df[col] = df[col].fillna(median_val)

In [63]:
# Convert numeric fields and fill missing
numeric_fields = ["mag", "depth_km", "nst", "dmin", "rms", "gap",
                  "magError", "depthError", "magNst", "sig"]

for col in numeric_fields:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val if not pd.isna(median_val) else 0)

In [64]:

df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day
df["day_of_week"] = df["time"].dt.day_name()

In [65]:
df["depth_flag"] = df["depth_km"].apply(
    lambda x: "shallow" if x < 70 else "deep"
)

In [66]:
def classify_mag(mag):
    if mag >= 7.0:
        return "destructive"
    elif mag >= 6.0:
        return "strong"
    else:
        return "moderate"

df["mag_flag"] = df["mag"].apply(classify_mag)

In [67]:
# Temporal features
df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day
df["day_of_week"] = df["time"].dt.day_name()

# Depth classification
df["depth_flag"] = df["depth_km"].apply(lambda x: "shallow" if x < 70 else "deep")

# Magnitude classification
def classify_mag(mag):
    if mag >= 7.0:
        return "destructive"
    elif mag >= 6.0:
        return "strong"
    else:
        return "moderate"

df["mag_flag"] = df["mag"].apply(classify_mag)

In [68]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,ids,sources,type,country,year,month,day,day_of_week,depth_flag,mag_flag
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,",us6000ddi8,",",us,",earthquake,Argentina,2021,1,31,Sunday,shallow,moderate
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,",us6000dev6,",",us,",earthquake,Fiji region,2021,1,31,Sunday,deep,moderate
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,",us6000dev5,",",us,",earthquake,Philippines,2021,1,31,Sunday,shallow,moderate
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,",us6000ddhs,",",us,",earthquake,Iran,2021,1,31,Sunday,shallow,moderate
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,",us6000dev4,",",us,",earthquake,Svalbard and Jan Mayen,2021,1,31,Sunday,shallow,moderate

In [69]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108801 entries, 0 to 108800
Data columns (total 33 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              108801 non-null  object
 1   time            108801 non-null  datetime64[ns]
 2   updated         108801 non-null  datetime64[ns]
 3   latitude        108801 non-null  float64
 4   longitude       108801 non-null  float64
 5   depth_km        108801 non-null  float64
 6   mag             108801 non-null  float64
 7   magType         108801 non-null  object
 8   place           108801 non-null  object
 9   status          108801 non-null  object
 10  tsunami         108801 non-null  int64
 11  sig             108801 non-null  int64
 12  net             108801 non-null  object
 13  nst             108801 non-null  float64
 14  dmin            108801 non-null  float64
 15  rms             108801 non-null  float64
 16  gap             108801 non-null  float64
 17  magError        108801 non-null  float64
 18  depthError      108801 non-null  float64
 19  magNst          108801 non-null  float64
 20  locationSource  0 non-null       object
 21  magSource       0 non-null       object
 22  types           108801 non-null  object
 23  ids             108801 non-null  object
 24  sources         108801 non-null  object
 25  type            108801 non-null  object
 26  country         108799 non-null  object
 27  year            108801 non-null  int32
 28  month           108801 non-null  int32
 29  day             108801 non-null  int32
 30  day_of_week     108801 non-null  object
 31  depth_flag      108801 non-null  object
 32  mag_flag        108801 non-null  object
dtypes: datetime64[ns](2), float64(11), int32(3), int64(2), object(15)
memory usage: 26.1+ MB

In [70]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\aravindhan\anaconda3\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [71]:
%%writefile global.py

import pymysql
import sqlalchemy as sqlalchemy

connection = pymysql.connect(
        host="localhost",        # or your server IP
        user="root",
        password="Aravindhan@0507",
        database="earthquakes",
        cursorclass=pymysql.cursors.DictCursor
    )

import sqlalchemy as sqlalchemy
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Aravindhan@0507@localhost/earthquakes")


import sqlalchemy as sa

engine = sa.create_engine(
    "mysql+pymysql://root:Aravindhan%400507@localhost/earthquakes"
)


   
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

# Dictionary of queries (already defined in your code)
queries = {
    "1. Top 10 strongest earthquakes":"""
    SELECT id, country, mag, place, time
    FROM quake_data
    ORDER BY mag DESC
    LIMIT 10;
    """,
    "2. Top 10 deepest earthquakes" : """
    SELECT id, country, depth_km, place, time
    FROM quake_data
    ORDER BY depth_km DESC
    LIMIT 10;
    """,
    "3. Shallow earthquakes < 50 km and mag > 7.5" : """
    SELECT id, country, mag, depth_km, place, time
    FROM quake_data
    WHERE depth_km < 50 AND mag > 7.5;
    """,
    "5. Average magnitude per magnitude type" : """
    SELECT magType, AVG(mag) AS avg_mag
    FROM quake_data
    GROUP BY magType;
    """,
    "6. Year with most earthquakes" : """
    SELECT year, COUNT(*) AS quake_count
    FROM quake_data
    GROUP BY year
    ORDER BY quake_count DESC
    LIMIT 1;
    """,
    "7. Month with highest number of earthquakes" : """
    SELECT month, COUNT(*) AS quake_count
    FROM quake_data
    GROUP BY month
    ORDER BY quake_count DESC
    LIMIT 1;
    """,
    "8. Day of week with most earthquakes" : """
    SELECT day_of_week, COUNT(*) AS quake_count
    FROM quake_data
    GROUP BY day_of_week
    ORDER BY quake_count DESC;
    """,
    "9. Count of earthquakes per hour of day" : """
    SELECT HOUR(time) AS hour_of_day, COUNT(*) AS quake_count
    FROM quake_data
    GROUP BY hour_of_day
    ORDER BY quake_count DESC;
    """,
    "10. Most active reporting network" : """
    SELECT net, COUNT(*) AS quake_count
    FROM quake_data
    GROUP BY net
    ORDER BY quake_count DESC
    LIMIT 1;
    """,
    "11. Reviewed vs automatic earthquakes" : """
    SELECT status, COUNT(*) AS count
    FROM quake_data
    GROUP BY status;
    """,
    "12. Count by earthquake type" : """
    SELECT type, COUNT(*) AS count
    FROM quake_data
    GROUP BY type;
    """,
    "13. Number of earthquakes by data type" : """
    SELECT types, COUNT(*) AS count
    FROM quake_data
    GROUP BY types;
    """,
    "14. Events with high station coverage" : """
    SELECT id, country, nst, mag, place
    FROM quake_data
    WHERE nst > 50;
    """,
    "15. Number of tsunamis triggered per year":"""
    SELECT year, COUNT(*) AS tsunami_count
    FROM quake_data
    WHERE tsunami = 1
    GROUP BY year;
    """,
    "16. Top 5 countries with highest avg magnitude (past 10 years)":"""
    SELECT country, AVG(mag) AS avg_mag
    FROM quake_data
    WHERE year >= YEAR(CURDATE()) - 10
    GROUP BY country
    ORDER BY avg_mag DESC
    LIMIT 5;
    """,
    "17. Countries with both shallow and deep earthquakes in same month":"""
    SELECT DISTINCT country, year, month
    FROM quake_data
    GROUP BY country, year, month
    HAVING SUM(CASE WHEN depth_km < 50 THEN 1 ELSE 0 END) > 0
       AND SUM(CASE WHEN depth_km > 300 THEN 1 ELSE 0 END) > 0;
    """,
    "18. Year-over-year growth rate in total earthquakes": """
    SELECT year,
           COUNT(*) AS quake_count,
           (COUNT(*) - LAG(COUNT(*)) OVER (ORDER BY year)) / 
           LAG(COUNT(*)) OVER (ORDER BY year) * 100 AS growth_rate
    FROM quake_data
    GROUP BY year
    ORDER BY year;
    """,
    "19. Top 3 seismically active regions":"""
    SELECT country, COUNT(*) AS quake_count, AVG(mag) AS avg_mag
    FROM quake_data
    GROUP BY country
    ORDER BY quake_count DESC, avg_mag DESC
    LIMIT 3;
    """,
    "20. Avg depth within ±5° latitude of equator":"""
    SELECT country, AVG(depth_km) AS avg_depth
    FROM quake_data
    WHERE latitude BETWEEN -5 AND 5
    GROUP BY country;
    """,
    "21. Countries with highest shallow-to-deep ratio": """
    SELECT country,
           SUM(CASE WHEN depth_km < 50 THEN 1 ELSE 0 END) /
           NULLIF(SUM(CASE WHEN depth_km >= 50 THEN 1 ELSE 0 END),0) AS shallow_deep_ratio
    FROM quake_data
    GROUP BY country
    ORDER BY shallow_deep_ratio DESC;
    """,
    "22. Avg magnitude difference between tsunami vs non-tsunami":"""
    SELECT AVG(CASE WHEN tsunami = 1 THEN mag END) -
           AVG(CASE WHEN tsunami = 0 THEN mag END) AS mag_diff
    FROM quake_data;
    """,
    "23. Events with lowest reliability": """
    SELECT id, country, gap, rms, mag, place
    FROM quake_data
    ORDER BY (gap + rms) DESC
    LIMIT 20;
    """,
    "24. Consecutive earthquakes within 50 km & 1 hour":"""
    SELECT a.id AS quake1, b.id AS quake2, a.time, b.time, a.place, b.place
    FROM quake_data a
    JOIN quake_data b
      ON a.id <> b.id
     AND ABS(TIMESTAMPDIFF(MINUTE, a.time, b.time)) <= 60
     AND ST_Distance_Sphere(POINT(a.longitude, a.latitude), POINT(b.longitude, b.latitude)) <= 50000;
    """,
    "25. Regions with highest frequency of deep-focus quakes":"""
    SELECT country, COUNT(*) AS deep_quakes
    FROM quake_data
    WHERE depth_km > 300
    GROUP BY country
    ORDER BY deep_quakes DESC
    LIMIT 10;
    """
}


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

st.markdown(
    "<h1 style='text-align: center; color: white;'>🌍 Earthquake Data Analysis</h1>",
    unsafe_allow_html=True
)

import streamlit as st

st.markdown(
    "<p style='color:red; font-size:18px;'>Select any problem statement:</p>",
    unsafe_allow_html=True
)


        
st.markdown(
    """
    <style>
    .stApp {
        background-image: url("https://static.vecteezy.com/system/resources/previews/030/637/247/large_2x/cracks-road-after-earthquake-damage-free-photo.jpg");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100% 100%;   /* Stretch to fill without cropping */
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown(
    """
    <style>
    /* Target selectbox label specifically */
    div[data-testid="stSelectbox"] label {
        color: white !important;   /* Change label text color */
        font-size: 26px !important;   /* Adjust font size */
        font-weight: bold !important; /* Make it bold */
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Selectbox with styled label
task = st.selectbox(label="Choose task number", options=list(queries.keys()))



if st.button("Run Query"):
    query = queries[task]
    df = pd.read_sql(query, engine)
    st.markdown(
    f"<h3 style='color: white;'>Results for: {task}</h3>",
    unsafe_allow_html=True
)
    st.dataframe(df, use_container_width=True)

    # Visualization logic for each query
    if task == "1. Top 10 strongest earthquakes":
        st.pyplot(df.plot(kind="bar", x="place", y="mag", color="red", legend=False,
                          title="Top 10 Strongest Earthquakes (Matplotlib)").figure)
        st.plotly_chart(px.bar(df, x="place", y="mag", color="country", title=task), use_container_width=True)

    elif task == "2. Top 10 deepest earthquakes":
        st.pyplot(df.plot(kind="bar", x="place", y="depth_km", color="blue", legend=False,
                          title="Top 10 Deepest Earthquakes (Matplotlib)").figure)
        st.plotly_chart(px.bar(df, x="place", y="depth_km", color="country", title=task), use_container_width=True)

    elif task == "3. Shallow earthquakes < 50 km and mag > 7.5":
        st.plotly_chart(px.scatter(df, x="depth_km", y="mag", color="country", hover_data=["place"], title=task), use_container_width=True)

    elif task == "5. Average magnitude per magnitude type":
        st.plotly_chart(px.bar(df, x="magType", y="avg_mag", color="avg_mag", title=task), use_container_width=True)

    elif task == "6. Year with most earthquakes":
        st.plotly_chart(px.bar(df, x="year", y="quake_count", title=task), use_container_width=True)

    elif task == "7. Month with highest number of earthquakes":
        st.plotly_chart(px.bar(df, x="month", y="quake_count", title=task), use_container_width=True)

    elif task == "8. Day of week with most earthquakes":
        st.plotly_chart(px.bar(df, x="day_of_week", y="quake_count", color="quake_count", title=task), use_container_width=True)

    elif task == "9. Count of earthquakes per hour of day":
        st.plotly_chart(px.line(df, x="hour_of_day", y="quake_count", markers=True, title=task), use_container_width=True)

    elif task == "10. Most active reporting network":
        st.plotly_chart(px.bar(df, x="net", y="quake_count", title=task), use_container_width=True)

    elif task == "11. Reviewed vs automatic earthquakes":
        st.plotly_chart(px.pie(df, names="status", values="count", title=task), use_container_width=True)

    elif task == "12. Count by earthquake type":
        st.plotly_chart(px.pie(df, names="type", values="count", title=task), use_container_width=True)

    elif task == "13. Number of earthquakes by data type":
        st.plotly_chart(px.bar(df, x="types", y="count", title=task), use_container_width=True)

    elif task == "14. Events with high station coverage":
        st.plotly_chart(px.scatter(df, x="nst", y="mag", color="country", hover_data=["place"], title=task), use_container_width=True)

    elif task == "15. Number of tsunamis triggered per year":
        st.plotly_chart(px.line(df, x="year", y="tsunami_count", markers=True, title=task), use_container_width=True)

    elif task == "16. Top 5 countries with highest avg magnitude (past 10 years)":
        st.plotly_chart(px.bar(df, x="country", y="avg_mag", color="avg_mag", title=task), use_container_width=True)

    elif task == "17. Countries with both shallow and deep earthquakes in same month":
        st.plotly_chart(px.scatter(df, x="month", y="year", color="country", title=task), use_container_width=True)

    elif task == "18. Year-over-year growth rate in total earthquakes":
        st.plotly_chart(px.line(df, x="year", y="quake_count", markers=True, title="Yearly Earthquake Counts"), use_container_width=True)
        st.plotly_chart(px.line(df, x="year", y="growth_rate", markers=True, title="Growth Rate (%)"), use_container_width=True)

    elif task == "19. Top 3 seismically active regions":
        st.plotly_chart(px.bar(df, x="country", y="quake_count", color="avg_mag", title=task), use_container_width=True)

    elif task == "20. Avg depth within ±5° latitude of equator":
        st.plotly_chart(px.bar(df, x="country", y="avg_depth", title=task), use_container_width=True)

    elif task == "21. Countries with highest shallow-to-deep ratio":
        st.plotly_chart(px.bar(df, x="country", y="shallow_deep_ratio", title=task), use_container_width=True)

    elif task == "22. Avg magnitude difference between tsunami vs non-tsunami":
        st.write("Magnitude difference:", df["mag_diff"].iloc[0])

    elif task == "23. Events with lowest reliability":
        st.plotly_chart(px.scatter(df, x="gap", y="rms", size="mag", color="country", hover_data=["place"], title=task), use_container_width=True)

    elif task == "24. Consecutive earthquakes within 50 km & 1 hour":
        st.plotly_chart(px.scatter(df, x="time", y="quake1", color="quake2", hover_data=["place"], title=task), use_container_width=True)

    elif task == "25. Regions with highest frequency of deep-focus quakes":
        st.plotly_chart(px.bar(df, x="country", y="deep_quakes", title=task), use_container_width=True)

    else:
        st.info("No visualization defined for this query yet.")

Overwriting global.py